export const UPDATE_DISPLAY_NAME_REQUEST = 'UPDATE_DISPLAY_NAME_REQUEST'
export const UPDATE_DISPLAY_NAME_SUCCESS = 'UPDATE_DISPLAY_NAME_SUCCESS'
export const UPDATE_DISPLAY_NAME_FAILURE = 'UPDATE_DISPLAY_NAME_FAILURE'