export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const FETCH_RIDES_REQUEST = 'FETCH_RIDES_REQUEST';
export const FETCH_RIDES = 'FETCH_RIDES';
export const FETCH_RIDES_FAILURE = 'FETCH_RIDES_FAILURE';
export const REQUEST_AUTO_RIDE = "REQUEST_AUTO_RIDE";
export const SUCCESS_AUTO_RIDE = "SUCCESS_AUTO_RIDE";
export const FAILURE_AUTO_RIDE = "FAILURE_AUTO_RIDE";
export const SETUP_LOCALSTORAGE = "SETUP_LOCALSTORAGE";

/****************************** Fetching User Profile Types ******************************/
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE'

/****************************** Updating User Profile Types ******************************/
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE'